"""Add quiz metadata fields

Revision ID: 874e6780a5cd
Revises: 
Create Date: 2025-06-19 18:07:27.220179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '874e6780a5cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('estimated_time', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('icon', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('author', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_column('author')
        batch_op.drop_column('description')
        batch_op.drop_column('icon')
        batch_op.drop_column('estimated_time')
        batch_op.drop_column('difficulty')

    # ### end Alembic commands ###
